### ISSUE TITLE
Address book does not show up in Android Contacts app

### ISSUE THREAD

**Issue by devurandom** [etesync/android#101]
In my EteSync account I have an address book named "Contacts". It shows up in the EteSync app, including a journal which suggests it should contain lots of contacts.

However, when opening the Android Contacts app, no contacts show. I go to Hamburger > Settings > Accounts and an "EteSync Address book" named "Contacts (email@example.com 1234)" shows up. I open that and it says "Account sync: Sync off for all items". I open that and it does not list any address books.

I open the Android system settings > Accounts, and I see an "EteSync" account named "email@example.com". When I open it, I see "Account sync: Sync on for all items". When I open that, I see "Address books" and "Calendar" with sync enabled for them.

In the list at system settings > Accounts, I also see an "EteSync Address book" named "Contacts (email@example.com 1234)". That is the same address book displayed to me by the Android Contacts app.

I already tried deleting my EteSync account and re-adding it, but that did not change anything.

EteSync: 1.9.5 (from F-Droid)
Hardware: Fairphone 3
OS: Android 9
Variant: Google, since there is no "Fairphone Open" (AOSP) for Fairphone 3, yet.
Build: 8901.2.A.0101.20191115

**Comment by devurandom** [comment]
The Google Play Store version of EteSync (version 1.9.6) suffers from the same problem.

Also noteworthy: In the EteSync app, under "Tasks", no task list shows up, while there should be two according to my EteSync desktop app. I do not have OpenTasks installed on my Android system, though.

**Comment by tasn** [comment]
Could you please try the following:
1. Uninstall the etesync app
2. Open settings -> Debug and enable log to file (you may also enable verbose logging but that may contain more personal information).
3. Add the account and let it sync.
4. Once you see the entries in the contacts journal send the log file.

If memory serves, disabling logging deletes the logs, so don't disable until you've sent the file.

Additionally, do you have other address books that still work? Did this used to work and a version update break it, or is it your first time on this phone? I guess it's fairly new to probably the first time, but still worth asking.

**Comment by devurandom** [comment]
> Could you please try the following:

Will have a look, but that will take a while. Please note that the contact data appears to be on the phone: I can see the contacts in the journal. It appears that the whole address book is not "visible" to Android: See the two EteSync accounts (instead of one) in system settings, with a funny name, one of them containing no syncable collections.

> Additionally, do you have other address books that still work? Did this used to work and a version update break it, or is it your first time on this phone? I guess it's fairly new to probably the first time, but still worth asking.

I freshly installed EteSync on the phone.

**Comment by tasn** [comment]
The two accounts and the weird name: that's normal. It's a workaround we have around the Android limitation of having only one address book per account. Don't worry (or touch!) the sync settings there.
Do calendars sync correctly or you haven't tested?

I wonder of fairphones use some sort of a non-standard compliant dialer and that's where the issues stems from. Do you see other accounts in the options in your contacts app?

**Comment by devurandom** [comment]
> The two accounts and the weird name: that's normal. It's a workaround we have around the Android limitation of having only one address book per account. Don't worry (or touch!) the sync settings there.

Confusing is that the email@example.com Android account that is just labelled "EteSync" has an address book and a calendar in its "accounts" / "Account sync" list, but the one with the "funny name" labelled "EteSync Address book" has nothing listed. And the latter is the only one listed in the "Contacts" app. Since I only have one address book in EteSync, why would you need two Android accounts?

> Do calendars sync correctly or you haven't tested?

The calendar is synced properly. The "Calendar" app shows the Google account (all Calendars disabled, account not synced) and "email@example.com", which I assume is EteSync. The calendar shows events that are definitely from my EteSync calendar.

> I wonder of fairphones use some sort of a non-standard compliant dialer and that's where the issues stems from. Do you see other accounts in the options in your contacts app?

I think the Fairphone OS comes directly from Google. The Calendar and Contacts app show "© 2019 Google Inc." when opening Hamburger > Help > Version info.

* Contacts: 3.13.0.281119312
* Calendar: 2019.45.1-279921459-release

When opening Hamburger > Settings > Accounts I see a lot of other accounts that I also saw in the Android system settings.

However, I cannot see any contacts from these in the main view... More confusing: In Signal (messenger) I can tap on a profile picture and see the contact's details. I can then tap the three dots > View linked contacts, and the contact is shown to have a linked contact in "EteSync Address book", which I can tap and see the details of that person... So maybe it is just Google Contacts being unable to get the contacts...?

**Comment by devurandom** [comment]
I figured it out... Unlike the AOSP Contacts app, the Google Contacts app is preset to only display contacts in the Google account. At the top right there is a small round icon, which one can tap (I just tapped it by accident, which is how I figured this out...) to display the different accounts to display contacts from.

What's remaining is the weird situation with one EteSync address book and multiple Android accounts, one of them being seemingly empty, but containing all contacts, while the other claims to contain an "Address book", but actually does not contain any contacts.

**Comment by tasn** [comment]
Great, so I'm closing this ticket, because it seems to be fixed.

Multiple accounts: again, ignore it, that's normal! The way EteSync (and DAVx5 and others) works is by having a main account that has a calendar and a fake address book (empty) and subaccounts for each address book.

So you seeing two accounts is absolutely normal. One is the fake general one, and one is the container for the address book you have. It's how it is, and as I said, it's because Android doesn't let you have multiple Address books unfortunately.
