### ISSUE TITLE
No sync! "Your subscription is inactive" (after payment!, Android app)

### ISSUE THREAD

**Issue by 19diesel86** [etesync/android#110]
Hi! Yesterday, in the transition from trial period to regular member, something went wrong and i cannot sync anything any more. I get the message "Your subscription is inactive, please check your dashboard", and the dashboard correctly shows my user is active.

Details: the payment was first blocked by the card issuer for confirmation. When I confirmed and the payment went through I was asked to log in again, successfully, but the app wouldn't sync any longer. I tried to remove the account, clear all data and start from scratch, but receive the "user inactive message"!

Any suggestion (since I am now left without contacts and calendar on my mobile?) :)

Thanks!

**Comment by tasn** [comment]
I don't know what happened, but I believe it's now fixed. I don't know why it didn't detect your payment, but I can see in the system you indeed paid.

If it isn't fixed please email support at support@etesync.com with your account information and we'll fix it for you immediately.

**Comment by 19diesel86** [comment]
Fixed, thanks a lot!

**Comment by tasn** [comment]
Great, and sorry again for the trouble.
