### ISSUE TITLE
/e/ build provides its own OpenTask and is not recognized by EteSync

### ISSUE THREAD

**Issue by tlaurion** [etesync/android#113]
This is a cross-post. [Documented on /e/ side here with screen captures.](https://community.e.foundation/t/impossible-to-install-opentasks/14542/7)

**Comment by tasn** [comment]
I wonder why EteSync doesn't detect their flavoured OpenTasks... Any idea what they changed or more information about the package name they used?

**Comment by tlaurion** [comment]
@tasn https://gitlab.e.foundation/e/backlog/-/issues/1221

**Comment by tasn** [comment]
I wonder if doing this also broke compatibility with external apps like EteSync, because we just use the OpenTasks library, so I think it should just work.

**Comment by tlaurion** [comment]
@tasn : let me know how I can provide you needed information by tagging me back.

**Comment by tlaurion** [comment]
```
adb: failed to install org.dmfs.tasks_78500.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package org.dmfs.tasks attempting to redeclare permission org.dmfs.permission.WRITE_TASKS already owned by foundation.e.tasks]
```

**Comment by tlaurion** [comment]
@tasn

**Comment by tasn** [comment]
I guess the best thing to check is to see if DAVx5 recognises their OpenTasks or not.

**Comment by tlaurion** [comment]
@tasn : and how one would do that?

**Comment by tasn** [comment]
Try to setup DAVx5 I guess, I'm not sure. I'm not a DAVx5 user, I just know it's another app that uses OpenTasks. If I had to guess though, it's probably something wrong with /e/, so probably better discussed with them.

**Comment by tasn** [comment]
We just added support for Tasks.org, though we got the patch form the Tasks.org developer. Maybe /e/ people can do the same?

**Comment by tlaurion** [comment]
Waiting for their next version to test. Poking them around would be nice

**Comment by tlaurion** [comment]
@tasn https://gitlab.e.foundation/e/backlog/-/issues/1221

**Comment by tasn** [comment]
OK, please keep me posted. Thanks!

**Comment by tasn** [comment]
I looked at it again, and it looks like they indeed just broke it and used their own name. We could support it, though really, maybe just install opentasks or tasks.org instead...

**Comment by tasn** [comment]
I'm happy to add support for their solution, though tbh, you should now use OpenTasks or Tasks.org, both supported by EteSync.
