### ISSUE TITLE
Some vCard 4.0 entries silently removed

### ISSUE THREAD

**Issue by Zvezdin** [etesync/android#114]
I've noticed that contacts which have been saved with instant messenger fields, as well as category fields, are immediately modified with the respective fields removed upon syncing between the front-end app and the EteSync client. Given how relevant these fields are I think that they should be supported, or the user should be at least notified about having some of the data they saved removed.

**Comment by tasn** [comment]
This shouldn't happen, and for all I know they are supported.
Could you please describe, step by step, what you did, with what app and what system? I'd like to be able to reproduce it locally so I can fix it.

Thanks for reporting!

**Comment by Zvezdin** [comment]
I tried to find a consistent way to reproduce the problem but after getting it to work a few times I think that the more likely explanation is that there was a problem with my frontend app instead.

However in the meantime I've noticed another issue which I can consistently reproduce in my test setup - one where removing a contact from a frontend gets reflected in the local contract state of the device app (and this change is visible multiple hours after the change, from multiple independent frontends), but does not get reflected in the journal. Other platforms syncing from the same database continue as if the contact was never removed. I'll probably need another issue for this, but since it's a very basic problem, I'm not sure if it doesn't happen to be a problem with my setup as well. Take a look at the following screenshot, taken some time after I've removed a contract from the frontend: 

![Screenshot_20200517-192906_EteSync](https://user-images.githubusercontent.com/15955296/82156761-045caf00-9875-11ea-898d-93b4bd16520e.jpg)

This is the whole journal history for this address book. This is taken a few hours after removing "Test 3" from a frontend. The change seems to be reflected in the contact count - which says 2, but from the journal history we can deduce that there should be 3 contacts. Any frontend reading from this database will also only show 2 contacts, except my etesync-dav on my desktop, which shows the full 3 contacts, again, multiple hours after the change, with all syncing enabled etc. In the meantime I have edited a contact's details and the changes got properly propagated through the system. 

Any thoughts?

**Comment by tasn** [comment]
Maybe sync isn't running automatically for you? What happens if you manually initiate a sync? If a change is not in the journal, it means it hasn't been pushed yet.

**Comment by Zvezdin** [comment]
I've forced sync multiple times throughout. Sync was working because the edits of "Test 1" and "2 Test" got logged and synced with my etesync-dav. Whereas the removal of "Test 3" (which took place before the edits) wasn't logged in the journal or synced externally, but was reflected in the screenshot above, where it says "Contacts: 2". 

The frontend that I've used to remove and update the contacts is: https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/

**Comment by tasn** [comment]
It's quite possible that the contacts app is doing something non-standard. Could you try another contact app and see if you are able to successfully delete contacts from it?

**Comment by Zvezdin** [comment]
I've also tried with the native Samsung contacts app with the same results (even though I think that they're more likely to be doing something non-standard as removing contacts is moving them to "the bin"). Actually a removed contact from from one app does not appear in the other either, indicating that they-re updating the contact state in a standard-compliant way, at least within android. This however doesn't get picked up by etesync. 

I also tried with this with the same results (removed contacts are not shown, removing a contact does not update the journal but the etesync app shows the real contact amount, as previously)https://f-droid.org/en/packages/com.bald.uriah.baldphone/:

**Comment by tasn** [comment]
The fact that they show each other's contact removal doesn't mean they are not doing something wrong. Because there are (slightly) different properties for sync adapters than for local contact apps. Anyhow though, the Samsung contacts app is known to work, so it's very unlikely this is the case.

Could you create test 4, sync so that it's in the journal, and then try removing it?

Could you please also close this ticket and open a new one describing this issue we are now describing?

**Comment by Zvezdin** [comment]
Moved to a dedicated issue
