### ISSUE TITLE
P2p? 

### ISSUE THREAD

**Issue by bijang** [etesync/android#116]
Is it possible to (similar to what matrix /riot) use server with libp2p client side and have completely p2p decentralised control?

**Comment by tasn** [comment]
In theory I guess it's possible, though I think it would be a distraction at this point. P2P solutions add a lot of value, but the complexity is just too much for the current size of the development team to handle, and I'd much rather focus on making EteSync better in other ways.

In summary: I'm open to the idea, but now is not the time.

Thanks for the suggestion though!
