### ISSUE TITLE
Login password incorrect msg after a few weeks on second device

### ISSUE THREAD

**Issue by fungs** [etesync/android#119]
On a Huawei CLT-L29/android 9 a working setup fails continuously after a few weeks usage with syc failed error. Reentering the login password recovers functionality.

**Comment by tasn** [comment]
How did you re-enter the login password? I think what may have happened is that your authentication token expired and it needed the login password to refresh it.

**Comment by fungs** [comment]
Just by using the original login password and entering it in the android app settings. I can't understand that on one phone it works but on the other it seems to "forget" it.

**Comment by tasn** [comment]
Does it happen consistently that this client "forget" its auth token, or is it the first time?
Does this other device sync well? And often? Maybe it doesn't sync often enough so its token just expires...

**Comment by fungs** [comment]
On that particular device it happend three times, the other is just working fine. Since it is a Huawei which is known having problems with power saving mode and background apps, I suspect something like you mention with the sync interval. Is there a way to maybe set the token expiry timeout somehow? I will check the sync history for the effective interval.

**Comment by tasn** [comment]
It's most likely this! Unfortunately there's no way to set the token expiry as it's a security mechanism. :|
Could you maybe take a look at: https://dontkillmyapp.com/huawei ? Maybe you can find a way to fix the device. :)

**Comment by tasn** [comment]
I'm closing this ticket as this has changed in etesync 2.0 and the issue probably doesn't exist anymore.

**Comment by fungs** [comment]
I can confirm this seems to be no issue any more using etesyc 2.0. thank you!
