### ISSUE TITLE
Integrity Error (Bad HMAC) although encryption password is correct

### ISSUE THREAD

**Issue by zeronymous** [etesync/android#123]
I'm unable to successfully sync my calendar and task list to my Android device.  
Here are the steps I've taken: 

**On my linux laptop:**
I registered an EteSync account and set up EteSync-Dav.
I subscribed to my calendar and task list in Thunderbird.  Thunderbird reports no errors.

**Then on my Android phone:**  Lineage OS17.1, Android 10
 I installed EteSync 1.14.0 from FDroid
Opened EteSync and clicked on the "+" button to add a new account
Logged in successfully with username and password.
When asked for my encryption password, I entered the value I got by logging in on my laptop and pressing the "copy password" button.  At this point a popup appears with the message "Wong encryption password.  Got an integrity error while accessing your account... Error: Bad HMAC..."  
I've verified several times that the encryption password i enter on my phone exactly matches the value from EteSync-Dav on my laptop, and that EteSync has storage, calendar, and contacts permissions enabled.  Turned on verbose file logging, but the contents don't reveal much - just  "Started deriving key...  Finished deriving key... Fetched user info for [username]... Wrong encryption password"
Updated EteSync to 1.15.1, but same issue persists

What other steps can I take to diagnose this?

**Comment by tasn** [comment]
Unfortunately EteSync uses case-sensitive email addresses as part of the encryption verification process, which means that if you put the same email in different casing in both you could get this error. Could you make sure you used the same casing in both?
This is already fixed in [EteSync 2.0](https://blog.etesync.com/coming-soon-etesync-2-0/) which should be released very soon.

**Comment by zeronymous** [comment]
I did notice the notes about case-sensitivity, and tried entering my username with all lowercase characters (the way I set it up on my laptop) and also tried capitalizing the first character, but neither way was successful.

**Comment by tasn** [comment]
You can also try https://client.etesync.com to test it out. Alternatively maybe email me ( tom @ the domain of the service) and I can help you figure it out.
