### ISSUE TITLE
Certificate fingerprint on Android

### ISSUE THREAD

**Issue by andreasmjg** [etesync/android#126]
Hi,

I updated Tasks.org to the latest version which includes Etesync support.

I also got the attached question. If the user is asked to verify a fingerprint, where can the user find the fingerprints for Etesync certificates? 

Thanks..! 
Andreas

**Comment by xeor** [comment]
I also all the sudden got this question, from cert4android.. what gives?

**Comment by abaker** [comment]
Sorry, this is a bug in Tasks! Fixed [here](https://github.com/tasks/tasks/commit/33f85f50cbb6e9ba08f05b844bf36801f185b276)

**Comment by tasn** [comment]
What's the bug @abaker? Maybe it's something it etesync too?

**Comment by tasn** [comment]
I uploaded a new apk to google play just now that should fix it, though I'm not sure.
https://stosb.com/~tom/etesync.apk if anyone wants to try it.

I have no idea why this would happen. The certificate is valid and works just fine here. I compared the fingerprint with users for whom it failed and it's the same.

**Comment by tasn** [comment]
Mystery solved! I finally managed to reproduce it locally and it's really just an issue with tasks.org. It doesn't pop up anything for etesync the app, only tasks.org. Grrr so much time sunk into this. :)
