### ISSUE TITLE
Build HowTo for version 2

### ISSUE THREAD

**Issue by thinkwelltwd** [etesync/android#140]
First of all, thanks for the excellent work on the etesync project!!

Is there a way to build v2 of this app? I'm not seeing a v2 branch or any reference to the updated protocol.

Thanks!

**Comment by tasn** [comment]
It's because it's already merged into master. :)
To build it, just build the master branch like you would any other Android app...

I'm closing this, as there's nothing to fix, but if you need help, please come to https://www.etesync.com/community-chat/

**Comment by thinkwelltwd** [comment]
Oh, thanks so much! and sorry for the noise.

**Comment by tasn** [comment]
No worries! :)
