### ISSUE TITLE
EteSync 2.0 login issue

### ISSUE THREAD

**Issue by bitog** [etesync/android#141]
Hi,

I just updated to EteSync 2.0 but it appears that I am not able to log into my account anymore. The new addition `Notes` works just fine. So I was wondering is there a new app to sync contacts and calendar? Maybe Etebase? I am currently running `EteSync 1.16.2 (114)`

**Comment by tasn** [comment]
The EteSync 2.0 Android app is not yet in Google play / f-droid (will probably be there in the next few days).
You should either build it yourself or use the prebuilt APK from: https://blog.etesync.com/etesync-2-0-ready-for-testers/

**Comment by bitog** [comment]
Just tried installing the `.apk` file however I am getting:

![img](https://i.imgur.com/d6wRlx8.png)

Do you by any chance have an idea how I could solve that issue?

**Comment by tasn** [comment]
Yeah, it's probably because you have EteSync installed from f-droid, and this apk is signed with the EteSync release key. You'll have to first uninstall the f-droid version before installing this one.
I'll update the blog post with more information.

**Comment by bitog** [comment]
Yes, that actually fixed it. Thank you!

**Comment by tasn** [comment]
Pleasure. :)
