### ISSUE TITLE
EteSync2 only showing 5 contacts on Android

### ISSUE THREAD

**Issue by Pleasantless** [etesync/android#148]
EteSync official android app (and web) shows all of my contacts within its EteSync2 account, and I checked that auto sync is on in ANdroid system settings. But many phone app state that only 5 contacts are available.

EDIT: after messing with it more, it now refuses to sync ANY contact into the phone but contacts sync into EteSync app and servers... so frustrating because I deleted everything. I know it is my fault for not checking the phone app but still.  I need to do my job!

**Comment by Pleasantless** [comment]
fixed by uninstalling app (not removing accounts).

**Comment by tasn** [comment]
Glad to hear a reinstall resolved it. I have no idea what went on, and can't guess without extra info. Though glad it's resolved.
