### ISSUE TITLE
After migrating to 2.0: Moving one event to a different time from a recurring event on Android doesn't update Etesync

### ISSUE THREAD

**Issue by makarandh** [etesync/android#154]
If there is a recurring event in a calendar, and if you move only one instance of the event to a different time, and then update it and sync Etesync, it doesn't update. 
This is happening after migrating to EteSync to 2.0. 

**Reproduction** **Environment**
1. Logged in to EteSync 2.0  
2. EteSync (Android)  version 2.1.5
3. Android Version 9.0 
4. Lineage OS version 16.0-20201112-microG-X00TD
5. Phone model: Asus X00TDA (XenPhone Max Pro M1)

**Reproduction steps:**
1. Migrate to Etesync 2.0 
2. On the android Etesync app, log in to Etesync 2.0 (with username and password, not email)
3. Let it sync calendar. 
4. Open phone's calendar app.
5. Create an event 'Test'. Date 2020-11-16 5:00 pm - 6:00 pm UTC. Set it to recurring every Monday 5:00pm-6:00pm, no end date.
6. Open Etesync app and click 'sync'
7. Open a browser on your computer, Log into EteSync 2.0 web app to see that the event has been correctly added.
8. On the android calendar app, edit the 'Test' item created for 2020-11-16. Change for this instance only (do not change the recurring events). Move it to Tuesday, 2020-11-17 5:00pm - 6:00pm. Make sure the rest of the 'Test' events for next Monday and so on are not changed. 
9. Switch to Etesync android app. Click sync. Wait for it to sync.
10. Open a browser on your computer. Log into EteSync 2.0 web app. The particular instance of 'Test' that was moved to Tuesday, 2020-11-17 was not updated. It still shows it's on 2020-11.16.

**Comment by tasn** [comment]
But it works on EteSync 1.0? Interesting, I'll have to take a better look, but I don't think we changed anything there.

**Comment by tasn** [comment]
I tested it locally and things work just fine for me. I'm also on lineageos and I use Etar as my calendar.

**Comment by tasn** [comment]
Any more information? Or should I close this?

**Comment by makarandh** [comment]
yes please go ahead and close it.

**Comment by tasn** [comment]
Glad to hear it's fixed.
