### ISSUE TITLE
Duplicates events on Android

### ISSUE THREAD

**Issue by MorgothSauron** [etesync/android#158]
I noticed that some events will show multiple times on Android. 

When I look on the web I have a single event for today. Same thing in thunderbird. But on Android that events shows about 15 times for the same day at the same time slot.

I had that problem few weeks ago and I "solved" it by deleting my account in the EteSync app and adding it back. 

I can see the duplicates in 2 different applications: Google Calendar and Simple Calendar.

![Screenshot_20201129-194944571](https://user-images.githubusercontent.com/6804228/100550746-e0424780-3273-11eb-904e-51b22a5a483c.jpg)

**Comment by tasn** [comment]
If you see them in two applications it's very likely that it's actually an issue with EteSync writing the events more than once. Which is very odd. A few questions:
1. What's your app version?
2. When you open e.g. the calendar app -> calendars to display. Do you see duplicate EteSync calendars? Or is it just the events that are duplicated?
3. Does it happen with all of the events or just new ones/ones you edit/some other subset?

**Comment by MorgothSauron** [comment]
> 1. What's your app version?

I have EteSync 2.1.5 installed from F-Droid running on a Redmi Note 8 Pro.

> 2. Do you see duplicate EteSync calendars? 

No duplicate calendars. Only few events get duplicated. From my example, I only had the "Clean Litterbox" events duplicated. Other events from the same calendar were ok.

> 3. Does it happen with all of the events or just new ones/ones you edit/some other subset?

It only happens with few events only and they were existing events I imported. 

Last night I did reset the EteSync app again (clear cache, clear data) and reconfigured it. Events that were showing as duplicates before are now showing properly.

**Comment by tasn** [comment]
Thanks for the info. How did you import them? Are you able to make it happen consistently? If you can, it can most likely easily be fixed.

**Comment by MorgothSauron** [comment]
Previously I was accessing my Nextcloud calendar with the DAVx application. I did the import on Android using the EteSync App. 

So far I didn't notice a pattern that could help me trigger the issue. It happened the 1st time last week. I reconfigured the EteSync app and everything was fine until yesterday.

**Comment by tasn** [comment]
OK, the problem was with one of the libraries we are using. Unfortunately upgrading it meant making a few changes. Could you try out https://stosb.com/~tom/etesync.apk (signed with the Gplay key) and let me know if it fixes it for you? I'll try testing it a bit more soon.
