### ISSUE TITLE
Tasks disappear after sync

### ISSUE THREAD

**Issue by Nurtyll** [etesync/android#163]
Hi,

I reported an issue, that the tasklist in tasks.org was empty after syncing the etesync 2.0 tasks to tasks.org:
[Issue#162](https://github.com/etesync/android/issues/162)

As suggested, by reinstalling both apps (tasks.org and etesync) the tasks were displayed. So the initial sync (after a fresh installation of both apps) with the ete-server does work, but when the eteSync-app does a second sync (automatic or triggered by user) the tasks in the app disappear and no task is shown...

I am using Fairphone Open 19.11.2 (Android 7.1.2) and the latest app versions from F-Droid.

Thank you for your help and have a nice day!

**Comment by tasn** [comment]
It's fixed in 2.2.0 which is not yet available on F-Droid. F-Droid builds sometime take time and it's outside of our control. :(
I'm closing this ticket as it's resolved, but if you have anything to add, please comment on #162 and I'll reopen it.
