### ISSUE TITLE
" potential vendor bugs" popup constantly showing 

### ISSUE THREAD

**Issue by dionisis84** [etesync/android#165]
Hi! I own a Xiaomi phone, and every time I open the EteSync app, the popup that warns about vendor bugs is showing, even though I select "don't show again" all the time! Minor bug!

**Comment by tasn** [comment]
Ah, what a silly mistake, nice catch!
Essentially the issue was that we were using the same flag for "battery optimisations" as for this, and I guess most people also deal with that dialog so it also marks this as handled. Releasing a version in a moment.
