### ISSUE TITLE
Tasks: Marking a (several times missed) recurring task as complete should mark the entire stack as complete

### ISSUE THREAD

**Issue by StoppingBuck** [etesync/android#171]
**Setup:** Set a recurring task to repeat every day, optionally set a reminder. Miss it for a couple of days. Then finally mark it as completed.

**What happens:** Only the first missed instance of the task is marked as complete, prompting the app (tasks.org's app in my case) to immediately pop the reminder for the next missed instance in the 'stack' of instances of the recurring task. Marking that one as complete causes the same thing with the third instance, etc. etc. Leaving me to click through a bunch of old instances of the task until I finally can mark today's task as complete.

**What should happen:** Marking the task as complete should implicitly mark the entire stack as complete and thus mark the latest instance of the recurring task as complete, regardless of how many missed instances have been before it (see the way Todoist handles recurring tasks for an example of this)

This same behavior happens with Thunderbird on the desktop making me suspect that it may be a universal problem. If this issue should be moved to a different issue tracker, let me know.

**Comment by tasn** [comment]
Hey, thanks for reporting!

I don't want to close the ticket prematurely, but I suspect it's not an issue with EteSync, but rather with the clients. Thunderbird and Tasks.org both handle how to split and close recurring tasks. We just do as we are told and sync that. I think opening a ticket with tasks.org is probably a better path to getting this fixed as I think the issue is probably there...

**Comment by abaker** [comment]
Tasks.org provides an option to repeat 'from completion' rather than 'from due date', but you're not likely to find this behavior in other clients because it is not part of RFC5545

**Comment by StoppingBuck** [comment]
Thanks for the replies, guys! I'll close this ticket myself and look into figuring things out with Thunderbird and find the option in Tasks.org that Alex mentions :)
