### ISSUE TITLE
App Crashes when re-entering encryption password

### ISSUE THREAD

**Issue by dalhousy** [etesync/android#18]
First run: Login with username and password and enter a new encryption password. It's successful and reminders can be added to the calendar.

Subsequently: Delete account on the Etesync app(on the client side) and re-enter the login details. App crashes after entering the same encryption password. Same issue when trying to login to the same account from a different phone.

I could be wrong, but it seems like the client app is trying to set an encryption password when it is already set in the first run?

Server details: Self hosted on a fresh Debian install, using the skeleton instructions.
Client details: App ver 0.19.1 from F Droid running on Lineage 7.1.2 and OmniROM 4.4.4

**Comment by tasn** [comment]
Hey,

Thanks for the report!

This is extremely weird, and I've never encountered it before. I'd assume you managed to insert a corrupted entry to the journal that for some reasons crashes it, though this obviously shouldn't happen!

Are you able to get me the exact crash log? (by for example using logcat?)

Additionally, could you please try accessing your account using the cli-client: https://github.com/etesync/cli-client

Unfortunately it doesn't support self-hosting yet, so you'd have to change the hardcoded remoteUrl here: https://github.com/etesync/cli-client/blob/master/etesync-cli#L14

Thanks for the info, and sorry for the trouble.

**Comment by dalhousy** [comment]
Thanks for the quick reply.

Unfortunately, I'm having a tough time trying to run the CLI client due to python errors and I don't have root access on the phone for easy logcatting.

Could I instead give you the server address and login details via a PM/Email so you can have a go yourself? Sorry for the trouble!

P.S. The app crashes no matter what the encryption password is, right or wrong.

**Comment by tasn** [comment]
Sure. My email is my first name @ etesync.com

--
Tom

**Comment by tasn** [comment]
Is this still an issue? A lot has changed... I'm closing this. Please reopen if still broken. I don't remember what we concluded over email.
