### ISSUE TITLE
android "send invitation to guests" doesn't generate the critical ICS to be parsed by the recipient

### ISSUE THREAD

**Issue by jzacsh** [etesync/android#182]
_"Send invitations to guests?"_ [android notification](https://github.com/etesync/android/blob/dbf7fdf634e071bfd6ca1c84269d3f723fe77bd3/app/src/main/res/values/strings.xml#L419) results in an email that doesn't have any attachment, so can't be machine-read.

I haven't dug through the pull request but https://github.com/etesync/android/pull/35 makes me think it's _supposed_ to send an ICS (which would be great!).

I've tested this with both protonmail android client and gmail android client, and sending to/from gmail accounts and between protonmail/gmail accounts.

- The etesync app installed is version `EteSync version: 2.2.4 (20204)`
- android version 11 (device: pixel 5)

**Comment by barathrm** [comment]
Android version 11
etesync version 2.2.4

FYI, when using the Etesync invite popup to share to *K-9 Mail* I do see an `invite.ics` file being attached, so it seems to work in some scenarios.

**Comment by jzacsh** [comment]
Update: while both Gmail and protonmail apps exhibit this bug for my, Tutanota doesn't (Tutanota pulls up a draft with an attachment shown)

**Comment by jzacsh** [comment]
protonmail magically started working :shrug: idk... feel free to reopen (anyone else) if you can reproduce.

**Comment by tasn** [comment]
I think they probably finally added support, they really never used to have it!
