### ISSUE TITLE
How big can contact photos be?

### ISSUE THREAD

**Issue by eternaltyro** [etesync/android#183]
How big can contact photos be to reliably sync between devices? I read somewhere they can be either 256x256 or 720x720. Is there a size maximum that etesync limits ?

**Comment by tasn** [comment]
vcard (the standard we use) is very inefficient with how it stores photos, so it's better to use smaller rather than larger photos. Hard to say about the exact size. Smaller is better, but there's no real limit, just increased resource (ram and storage) use when you use larger sizes.
