### ISSUE TITLE
Android app "sync failed" authentication failed

### ISSUE THREAD

**Issue by MartyLake** [etesync/android#186]
Hello,

Recently, Etesync on Android (from FDroid) gives me an error:
```
Sync failed (martylake)
Authentication failed
```
When I go to the app's account's settiongs, if I click on "Manage Account > Account Dashboard", it get a toast notification "An error has occured. Invalid token".

How do I refresh the token ? I don't want to delete and add the account, as I have unsynced data on my phone at the moment.

Best,

**Comment by MartyLake** [comment]
I tried to grep the strings, it seems that:

* the notification comes from https://github.com/etesync/android/blob/f0b19e8c3846510a7e234ca19d41289bbdf1327e/app/src/main/java/com/etesync/syncadapter/syncadapter/SyncAdapterService.kt#L132-L150
* because https://github.com/etesync/android/blob/f0b19e8c3846510a7e234ca19d41289bbdf1327e/app/src/main/java/com/etesync/syncadapter/syncadapter/SyncNotification.kt#L42-L44

then I don't know, maybe it's because of :

* https://github.com/etesync/etebase-java/blob/721cb3056ec01152ea3e5c85df57aa30cb21ee89/src/jni_typemaps.rs#L19
* https://github.com/etesync/etebase-rs/blob/70a2db69c51149d1b2d1a82d11e1882d3c1ec660/src/http_client/client_impl.rs#L103
or
* https://github.com/etesync/etebase-rs/blob/3a9df33403fb6911e97370e7b513bfaf52bfdbee/src/error.rs#L30

which maybe comes from:
* https://github.com/etesync/server/blob/58163d6678be29f80b930abe4bb6d2089945eb9c/etebase_fastapi/routers/authentication.py#L171-L172

All of that makes it feel like the password I have in the Android app is wrong. Is there a way to refresh the password without deleting + adding the account again ?

**Comment by tasn** [comment]
Invalid token means that you need to logout and log back in. It's annoying indeed, we'll increase the expiry time, though we are doing it for security.

**Comment by MartyLake** [comment]
Dear tasn. Unfortunately, I have switched to nextcloud because of this issue and I am no using your app anymore. Thank you suggesting a workaround though.

**Comment by tasn** [comment]
No worries, all the best!
