### ISSUE TITLE
Got an unknown certificate error

### ISSUE THREAD

**Issue by BlazeFrog** [etesync/android#191]
EteSync has encountered an unknown certificate. Do you want to trust it?
X509 certificate details
issued for: 
[2]api-test.etebase.com [2]api.etebase.com
[2]dashboard.etebase.com
[2]devs.etebase.com [2]docs.etebase.com
[2]etebase.com [2]www.etebase.com
Issued by
CN=R3, O=Let's Encrypt, C=US
valid period 
June18,2021 - September 16,2021 (Will not be enforced)
Fingerprint
SHA-256: 12:5d:e7:44:a2:05:f9:21:1f:b9:e7:9b:d0:91:38:7b:8e:06:0a:c7:ac:e1:ba:0d:b8:da:06:d2:66:2a:74:38

Also in my case should I accept or reject? I'm not sure where to check if it is valid or not. Thanks

**Comment by hepaajan** [comment]
I think it has just expired and we need to wait until it's renewed.

**Comment by bigfatfrog67** [comment]
How long should we wait?

**Comment by tasn** [comment]
Sorry about that, it's now been fixed. It was meant to be an automatic process but it failed. Not sure why, investigating.
