### ISSUE TITLE
The change journal should display important information for the normal user

### ISSUE THREAD

**Issue by JackDanielZ** [etesync/android#20]
Hi,

When I open the change journal, I see all the UIDs and try to understand how it can really help me on a daily basis - without success.
Why not giving the user a default log view with name, date, hour? Then one could change the information displayed (UID, location...) via settings.
In this way, it could provide everyone the best UX adapted to his needs.

Daniel

**Comment by tasn** [comment]
Thanks for your comment. I like the UID as it shows me which items are the same, but I guess this may not be true for everyone, so it at the very least shouldn't be this prominent.

As for the rest of the info: unfortunately parsing vobjects is very slow (on android?), so I have to pre-calc (cache) what I want to show there. It can be done, but it's quite a bit of work with not a lot of obvious benefit. I'll try to get to it.

**Comment by Zvezdin** [comment]
I would agree that having at least a timestamp of the journal items would be very useful in visualization.

**Comment by tasn** [comment]
I agree. I took a look at it again and implemented the change, though the main problem is that the modified date is not currently mandatory so things looked a bit odd.

We are working on some changes that should make this possible in the near future though, so stay tuned! :)

**Comment by tasn** [comment]
Fixed in EteSync 2.0
