### ISSUE TITLE
Potential HTTP APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [etesync/android#206]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 32 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on etesync-android (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve etesync-android's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by tasn** [comment]
Please report to: security @ the domain

Though I guess that since you already gave a link to the analyzer used to find things it's public knowledge anyway, so you may as well just post it here and we can have a discussion here.

I find it quite unlikely that there are real issues though, because this application doesn't actually power the cryptographic code in EteSync. The code is written in Rust and resides in Etebase-Java...

**Comment by misterAnderson90** [comment]
Hello @tasn,

From the 32 warnings that CogniCrypt reported, we selected 5 gists to share with you. Four of them are related to the class [HTTPClient.kt](https://github.com/etesync/android/blob/f0b19e8c3846510a7e234ca19d41289bbdf1327e/app/src/main/java/com/etesync/syncadapter/HttpClient.kt). The remaining warnings are related to third-party libraries. As an example, I'm sharing with you the Gist 05 related to [okio/ByteString.kt](https://github.com/square/okio/blob/master/okio/src/commonMain/kotlin/okio/ByteString.kt). 

[Gist 01 - SSLContext](https://gist.github.com/misterAnderson90/6ed517a0fb3171f840cffcf31722db64)
[Gist 02 - SSLContext](https://gist.github.com/misterAnderson90/f6abffd18a8e09ffddc8330b47b49911)
[Gist 03 - KeyStore](https://gist.github.com/misterAnderson90/322703ef1fda71854580018329d12892)
[Gist 04 - SSLContext](https://gist.github.com/misterAnderson90/0c4a264e3e8c4cc3c59f7db9dd642df1)
[Gist 05 - MessageDigest](https://gist.github.com/misterAnderson90/4936551fc5f104d40ee4b48b5679d8a4)

For any doubts, you can comment here and/or directly in the gists and we can clarify the issues.  

Please let me know whether you are interested in receiving the complete report with the remaining warnings related to third-party libraries used by etesync/Android. 

Best regards,

**Comment by tasn** [comment]
I don't think you can report spammers, no?

But anyway, closing this ticket, as it was nonsense from the start.
