### ISSUE TITLE
Checking off many tasks results in sync issue

### ISSUE THREAD

**Issue by sawft99** [etesync/android#214]
Checking off many tasks results in sync issue When syncing a lot of task changes I run into the error below now. I'm using the tasks.org app 12.7.1. If I make many changes to my tasks, I mean 5 or so at once, and resync this error appears. I deleted my phone data and redownloaded from Ete. I was able to get the same result each time. If I do one at a time and then sync after each one, then it goes through. Upon going back to doing several at once, this brings the same error back I am running GrapheneOS so ill try to play with the settings some. Nothing has worked yet. Unless a recent update for the OS would have changed the config, then the apps and systems should not have changed. Except whatever the updates for apps and OS brings. This started happening a bit over a week ago

--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO
Synchronization phase: pushing entries
Account name: wf4
Authority: org.tasks.opentasks
Debug activity source: class com.etesync.syncadapter.syncadapter.SyncNotification$NotificationHandlerActivity (Kotlin reflection is not available)

EXCEPTION:
com.etebase.client.exceptions.ServerErrorException: Server error
	at com.etebase.client.ItemManager.do_batch(Native Method)
	at com.etebase.client.ItemManager.batch(ItemManager.java:96)
	at com.etebase.client.ItemManager.batch(ItemManager.java:189)
	at com.etesync.syncadapter.syncadapter.SyncManager.pushItems(SyncManager.kt:593)
	at com.etesync.syncadapter.syncadapter.SyncManager.performSync(SyncManager.kt:235)
	at com.etesync.syncadapter.syncadapter.TasksSyncAdapterService$TasksSyncAdapter.onPerformSyncDo(TasksSyncAdapterService.kt:70)
	at com.etesync.syncadapter.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:117)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)

SOFTWARE INFORMATION
EteSync version: 2.3.0 (20300) 
Installed from: com.android.packageinstaller
CONFIGURATION
Power saving disabled: yes
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: denied
org.dmfs.permission.WRITE_TASKS permission: denied
org.tasks.permission.READ_TASKS permission: granted
org.tasks.permission.WRITE_TASKS permission: granted
System-wide synchronization: automatically
Account: wf4
  Address book sync. interval: 240 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: —
  Tasks.org    sync. interval: 240 min
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
           Manage calendar colors: true
Address book account: My Contacts (wf4 Wg)
  Main account: Account {name=wf4, type=com.etesync.syncadapter}
  URL: xxxxx
  Sync automatically: true

SQLITE DUMP
android_metadata
	|  locale |
	|  en_US |
----------
settings
	|  setting | value |
----------

SERVICES DUMP

JOURNALS DUMP

SYSTEM INFORMATION
Android version: 13 (TP1A.221005.002.2022101600)
Device: Google Pixel 5a (barbet)

--- END DEBUG INFO ---

**Comment by ImranR98** [comment]
Exact same issue here, also on GrapheneOS.

**Comment by sawft99** [comment]
> I'm having the same error for days now. I saw people talking about it on Reddit I didn't see any answer from the devs until now

For Graphene, Etesync, or something else?

**Comment by sawft99** [comment]
No problems anymore since graphene 10/18 update. So a graphene issue probably.
