### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [etesync/android#224]
```
Fetched in submodule path 'ical4android', but it did not contain b62dfc46f61aa310a65383e7b99f66a99959da2b. Direct fetching of that commit failed.
```

Could you please take a look? Thanks!

**Comment by tasn** [comment]
Missing push for a dep, whoops. Fixed now!

Can the f-droid build be retriggered, or do we need to release a new version? This repo hasn't change at all, it's the repo of one of the deps.

**Comment by linsui** [comment]
Thanks! It will be built in the next build cycle.

**Comment by tasn** [comment]
Awesome, thanks!
