### ISSUE TITLE
EteSync 2.4 on Android 13 not syncing tasks

### ISSUE THREAD

**Issue by NJCLous** [etesync/android#226]
Hi Tom,

EteSync 2.4 on Android 13 (on a OnePlus 9 Pro phone) seems to have stopped syncing tasks using OpenTasks. 

Symptom: If I open EteSync on the phone and tap my account, I see Contacts and Calendar both syncing properly, but Tasks has a notification "Not syncing tasks (install a provider)". The task list is headed "Change Journal" and states "Log is only shown if a task provider is installed". I have OpenTasks installed and set permissions for EteSync, OpenTasks and my calendar app aCalendar+ to access Tasks. All apps are allowed background access.

Tried and failed: I tried uninstalling EteSync and OpenTasks, then reinstalling (EteSync first, then OpenTasks) but that didn't help. I then uninstalled EteSync and OpenTasks again, reinstalled installed EteSync and enabled "Prefer Tasks.org" (as you suggested in another issue) before reinstalling OpenTasks. That didn't help either.

In EteSync on the phone, if I tap my account, then the hamburger menu to the right of the word "Tasks", a pop-up menu appears with options "Create task list", "Install Tasks.org" and "Install OpenTasks". This suggests OpenTasks is still meant to work with EteSync 2.4.

How can I reconnect EteSync to OpenTasks and get syncronisation going again? 

Your help is much appreciated!

**Comment by barathrm** [comment]
This might not help you if you prefer opentasks, but have you tried tasks.org? https://f-droid.org/en/packages/org.tasks/

FWIW, etesync 2.3 + opentasks 1.4.2, both from f-droid, are both working fine for me on Android 13 (graphene os). You could try those versions and see which one works for you so we can try to narrow down the issues come from.

**Comment by tasn** [comment]
I suspect it's because the installation caused it to "undetect" it. Maybe try installing tasks.orgs and seeing if it makes it detect open tasks? Or try reinstall opentasks?

**Comment by NJCLous** [comment]
Hi barathrm and Tom,

I tried Tasks.org which doesn't connect with EteSync either. I did the following for Tasks.org:

- Uninstall all relevant apps (EteSync, Task.org and/or OpenTasks);
- Install Tasks.org 13.3.2 from Google Play;
- Give both apps all requested permissions, including background activity;
- Open Tasks.org and add my EteSync account. My tasks appear in Tasks.org.
- Open EteSync 2.4.0 and add my EteSync account. Contacts and Calendar sync as expected, but under Tasks I get the message "Not syncing tasks (install a provider)".

Also, Tasks.org. does not sync with my calendar app aCalendar+ which wants me to use OpenTasks....

...so I proceeded as follows for OpenTasks:
 
- Uninstall all relevant apps (EteSync, Task.org and/or OpenTasks);
- Install OpenTasks 1.4.2 from Google Play;
- Give both apps all requested permissions, including background activity;
- Open OpenTasks - which works but there is nowhere there to "connect" to EteSync;
- Open EteSync 2.4.0 and add my EteSync account. Contacts and Calendar sync as expected, but under Tasks I get the message "Not syncing tasks (install a provider)".

...so no luck.

I have no experience with F-droid and would prefer to stick with Google Play for practical reasons. It would make sense to try the previous version of EteSync but I don't know how to get that onto my phone.

Further help is much appreciated!

Niels

**Comment by NJCLous** [comment]
PS: It might be relevant that my OnePlus 9 Pro uses OxygenOS 13.1 (based on Android 13, but I guess with some OnePlus-typical variations).

**Comment by frostynumeral** [comment]
I have the same issue with two Samsung devices (phone and tablet). Both are running Android 13 from the manufacturer. I'm using etesync and tasks.org installed from the Play Store. Tasks synchronization was working fine with the previous version, but now no longer.

I have tried uninstalling and reinstalling both etesync and tasks.org, but it didn't resolve the issue.

**Comment by letscho123** [comment]
I have the same issue on Google Pixel 4a with CalyxOS (Android 13) since the latest version. Downgrading EteSync to the previous working version did give an error on F-Droid.

**Comment by barathrm** [comment]
I can confirm that updating to etesync 2.4 from f-droid, etesync now says `* Not syncing tasks (install a provider)`. I have OpenTasks 1.4.2 installed. Looking at the etesync debug logs, etesync says this at startup:

```
2023-06-11 16:38:34 14 [com.etesync.syncadapter.AccountSettings] Account barath has version 2, current version: 2
2023-06-11 16:38:34 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (false) for OpenTasks
2023-06-11 16:38:34 14 [com.etesync.syncadapter.AccountSettings] Account barath has version 2, current version: 2
2023-06-11 16:38:34 14 [com.etesync.syncadapter.utils.TaskProviderHandling] Package (un)installed; Syncing (false) for TasksOrg
```

Downgrading directly is not possible (I get an error), **however uninstalling etesync and manually installing version 2.3 makes it work fine, like before**. So it seems like something about version 2.4 breaks detection of task "providers" (OpenTasks, Tasks.org).

**Comment by marcdw1289** [comment]
Testing among my other devices / ROMs.
This issue does not exist on my Oreo (XenonHD on Moto G5s Plus) or Pie (Havoc-OS on Moto G5 Plus) ROMs. Well, no 'Not syncing tasks' message. Haven't actually tested task syncing as I never use it.

On two Android 11 devices with crDroid (OnePlus 8T) and Leos-R GSI (Essential PH-1) the issue exists.

Haven't dug into the differences yet.

**Comment by networkdudee** [comment]
Same issue on Android 12 Galaxy S10 #228

**Comment by NJCLous** [comment]
Hi Tom or EteSync colleague - it appears that several people run into this issue on a number of phones / Android versions. Reverting to EteSync 2.3 is mentioned as a temporary fix. Could you please make EteSync 2.3 available via the Google Play Store, or issue a fix to EteSync 2.4 via that channel? I don't use F-droid and don't have the expertise (or time) to get it installed. Thanks, also to all who contributed to this issue, and best regards - Niels

**Comment by tasn** [comment]
I wonder if something happened because of the target SDK difference that doesn't let us do this anymore because that's the main thing that changed. I won't have time to look at it in at least a couple of weeks unfortunately. :(

**Comment by NJCLous** [comment]
Hi Julian - thanks for explaining how to install EteSync 2.3 without F-Droid! For other APK novices like myself: I had to uninstall EteSync 2.4, and allow apps from "other sources", before my let me install the APK for EteSync 2.3.

Tom - I hope you'll manage to make task syncing work with the new target SDK. If fixing the issue will take a couple of weeks at least, perhaps a notification on the website and within the app would reduce the number of questions about this.

**Comment by pkonow** [comment]
Can confirm that uninstalling EteSync version 2.4 and installing version 2.3 from F-Droid fixes the problem on GrapheneOS.

Btw. in F-Droid you can tap in the top right corner and select "Ignore this update" to skip version 2.4 and wait for the next update instead.

**Comment by Sch1nken** [comment]
Just to have a few more datapoints. I noticed the syncing issues too using etesync 2.4 on android. In fact, I worked on my phone (Android 10) but we had a lot of trouble with my SO's phone (Android 11). It always displayed a message about no task-handler(?) being installed. We tried manually giving all permissions (through the android settings) to no avail.

I tried Android 10 through 13 in an AVD Emulator. 10 works out of the box with 2.4. On all higher versions 2.4 does NOT work. 2.3 on the other hand works fine on all versions.

**Comment by Sch1nken** [comment]
Okay, I think I've found the problem. I poked around a bit and tried specifying "needed" package names explicitly like mentioned here: https://developer.android.com/training/package-visibility/declaring#package-name

I tried it with the fdroid opentasks package name (org.dmfs.tasks) and that at least got rid of the pesky "no provider" message (Android 11 in AVD Emulator).

So I think just adding 
```XML
    <queries>
        <package android:name="org.dmfs.tasks" /> 
        <package android:name="org.tasks" />
    </queries>
```

For opentasks and tasks.org respectively should do the trick on SDK Level 30+ and Android 11+.
I'll see if I can provide a pull request tomorrow. In the meantime maybe someone is willing to do some more testing with this solution.

Also: As described in https://developer.android.com/training/package-visibility/automatic there are several ways for automatic discovery, though I am not good enough with android development to know what would fit.

**Comment by tasn** [comment]
F-droid should be building, and Google Play is out for review.

**Comment by NJCLous** [comment]
Thanks Tom! I'm glad Sch1nken and you manage to resolve the issue and look forward to the updated EteSync app. Best regards - Niels

**Comment by tasn** [comment]
> Thanks Tom! I'm glad Sch1nken and you manage to resolve the issue and look forward to the updated EteSync app. Best regards - Niels

Only @Sch1nken deserves the credit!

**Comment by Sch1nken** [comment]
You're welcome! :)
