### ISSUE TITLE
Android 12 EteSync 2.4.0 Crash on Sync to Server

### ISSUE THREAD

**Issue by networkdudee** [etesync/android#228]
I subscribe annually to an etesync server. I noticed my task list wasn't synchronising across devices. So, I uninstalled etesync, reinstalled and when it tries to sync it crashes everytime.

**Comment by networkdudee** [comment]
![Screenshot_20230613-043650](https://github.com/etesync/android/assets/117722576/e2fd85c6-dbea-4397-a161-c9ca2b496448)

When it tries to sync tasks it crashes. I use OpenTasks 1.4.2

**Comment by networkdudee** [comment]
Sorry closed issue by accident. I've tried uninstalling etesync and opentasks and reinstalling etesync followed by opentasks but no joy!

**Comment by haadr** [comment]
Duplicate of https://github.com/etesync/android/issues/226

**Comment by networkdudee** [comment]
Workaround! Issue not present in v2.3 of etesync (available on F-droid).

**Comment by tasn** [comment]
Yay, thanks for closing this! :)
