### ISSUE TITLE
Syncing issue 

### ISSUE THREAD

**Issue by Airedale37** [etesync/android#229]
Like others are experiencing, I am having trouble with syncing. For me it is with Tasks.org and etesync. No problems with my calendar or contacts just the task app. It's been saying that I need to install a provider. The last time it looks like it synced was 6/2/23. Though I think it's been saying that for a couple months. I have an LG V60 android 13. What should I do?

**Comment by tasn** [comment]
Duplicate of https://github.com/etesync/android/issues/226
