### ISSUE TITLE
Android App Crashes on Sync

### ISSUE THREAD

**Issue by flscinfo** [etesync/android#233]
Good morning,
Since Friday, June 30th, 2023, my Android EteSync App crashes on attempted sync. The error occurs while using WiFi as well as while using mobile data.

Versions:
- Android, version: 12
- Android, kernel version: 4.19.157-perf+{hashtag}1 Wed May 10 19:42:53 CST 2023
- Android, build number: FP4.SP29.B.069.20230510
- EteSync, version: 2.4.1

Deinstalling the app, rebooting and re-installing does not fix the problem.

I would be very grateful for any help, as it's important for me to be able to sync my data.

Best,
Florian

**Comment by tasn** [comment]
Grr. Do you have any additional info? E.g. the reason for the crash?

**Comment by flscinfo** [comment]
No, unfortunately not. It seems to crash on callendar sync (independently whether I sync in EteSync or my callendar app "Simple Callendar Pro", version 6.21.9).

Please find the crash massage attached (strack trace already uploaded to the developers).
![Screenshot_20230704-111221_1](https://github.com/etesync/android/assets/132125858/90ed381b-dead-4bd1-8805-bcc6517bbb97)

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
I just encountered the same issue with the same versions of Android (12) and EteSync (2.4.1).
I also sent the stack trace using the crash message pop up.

**Comment by tasn** [comment]
Thanks for the info! Immediate workaround: downgrade (maybe using f-droid?) and I'll take a look in the meantime.

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
I can confirm the workaround - downgrading to 2.4.0 using f-droid worked.
Thank you for your immediate response!

**Comment by tasn** [comment]
I'm pretty sure I found the issue, fix incoming.
