### ISSUE TITLE
Android 11 etesync v.2.4.2 Tasks Sync Failed

### ISSUE THREAD

**Issue by networkdudee** [etesync/android#240]
Error while creating local entries. Using tasks.org. Samsung Galaxy A50.

**Comment by barathrm** [comment]
Does updating to etesync v2.4.3 fix the issue for you?

**Comment by networkdudee** [comment]
Apologies, no longer using ete anymore but thank you for following up.

**Comment by barathrm** [comment]
Alright np, in that case would you mind closing the issue @networkdudee? I

**Comment by shvchk** [comment]
Had the same issue, 2.4.3 fixed it for me
