### ISSUE TITLE
No synchronisation (tasks and contacts) [EteSync 2.4.2 | OnePlus 8 Pro Android 13]

### ISSUE THREAD

**Issue by z-master42** [etesync/android#241]
I noticed that my tasks have not been synchronised since 5 June, i.e. everything I had entered on my mobile phone since then. I played around in the app and more or less accidentally restored the last synchronisation status, i.e. the one from 5 June. I saved all my tasks in text files and created new tasks to experiment with.

When I change a task on my PC (in Thunderbird), this change is transferred to the server, but when I look in the app, the modification date of this task has not changed, only when I go into the revisions do I see this change. Neither the OpenTask nor the Tasks.org app shows the change.

![grafik](https://github.com/etesync/android/assets/66380371/72898b61-7301-4810-a22d-a1ac0a1f75a8)

I then reinstalled and set up the app, nothing has changed in the status of the tasks, **but now my contacts are also no longer synchronised**. 

The only thing that still works without problems is calendar synchronisation.

No errors are displayed in the debug info.

**Comment by z-master42** [comment]
Perhaps a duplicate of [#235](https://github.com/etesync/android/issues/235).

**Comment by tasn** [comment]
Contacts: can you describe in more detail what you're seeing? Tasks: I also noticed it and will try to figure it out. It's because of the target SDK changes most likely. :|

**Comment by z-master42** [comment]
I don't see anything, that's the problem. In Thunderbird address book I see my contacts and they are also in sync with the server. But on my phone is only an empty collection.

**Comment by barathrm** [comment]
> Contacts: can you describe in more detail what you're seeing?

I have the same, for *some* calendars, *some* tasks collections etc. They simply appear empty, and I can't find any likely culprits in the logs (though I'm not an android dev).

**Comment by face0b1101** [comment]
I've just moved to android 13 (Google Pixel 7 Pro) and I'm seeing similar behaviour with contacts and calendars (I'm not using tasks).

My old phone and wife's phone sync or shared calendars and the full change journal is visible. On the new Pixel local changes are pushed, but all remote calendar entries are not pulled. There is also either no, or incomplete (and very old), history in the calendar change journal.

**Comment by z-master42** [comment]
My contacts did sync now since my last post, without me doing anything. I don't know exactly when, probably from yesterday to today. Regarding my tasks, however, the problem persists.

**Comment by z-master42** [comment]
Got the Android app update today, looks like everything is working again. Thanks!

**Comment by tasn** [comment]
Awesome! Sorry for the trouble.
