### ISSUE TITLE
Bitcoin, Litecoin ids on fdroid metadata

### ISSUE THREAD

**Issue by jindam-vani** [etesync/android#243]
@tasn 
* **your explicit consent is required** to add Bitcoin ```1JabgDMY1b7BiQXZyTBiqU9uFjejmdekjk``` and Litecoin ```MFWt9P7FvQGKrSDJFDCFVWRtmQWF2qxo72``` given at  https://www.etesync.com/contribute/#donate in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.etesync.syncadapter.yml)
* both ids are not given in repo, hence this request
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by tasn** [comment]
Thanks for the ping, I didn't realize we still had that there (I just removed it)!
Even though control the addresses (so if money was sent it wasn't lost), we decided to stop accepting crypto donations for now. 

The amounts were very low, and the accounting/compliance headache was just more than it's worth. :(

So let's not add it for now, but thanks again for the ping!
