### ISSUE TITLE
No more synchronisation

### ISSUE THREAD

**Issue by z-master42** [etesync/android#246]
Hello, as I have noticed over the last few days, the synchronisation of my calendars and tasks has not worked since mid-September. Has anything been changed/adjusted in the background? The last time (#241) was fixed quite quickly.

**Comment by tasn** [comment]
We are not aware of anything. One thing you can try:
**IMPORTANT:** Without logging out of your account
Try to add the same username + password again to the Android app and see if it fixes it. please let me know if that's the case.

**Comment by z-master42** [comment]
I restarted my device and then tried logging into the app again with the same data. I was shown a blank page, but it seems to have been the solution, the data was synchronized.

**Comment by tasn** [comment]
Awesome! Please let me know if this comes back.

I wonder what caused it.

**Comment by z-master42** [comment]
Hello, it's me again! Once again it doesn't work, this time restarting and logging in again without logging out doesn't bring the desired success... I don't know why.
