### ISSUE TITLE
REQ: Contact Groups

### ISSUE THREAD

**Issue by LogicalDash** [etesync/android#25]
I'm not sure if this is implemented in the protocol or what? Currently, I cannot assign groups to any of my contacts in an EteSync address book. I should be able to do that.

**Comment by tasn** [comment]
It is implemented, and it works, I just used it today.
What app do you use for your address book? Does it work for you for other account providers? (e.g. Google)

**Comment by LogicalDash** [comment]
It's the contacts app that comes with OxygenOS 5.0.1 Android 8.0.0. The Add Group dialog lets me pick an account to make it under and I can do Google or Phone, but not EteSync.

Same behavior in GO Contacts EX.

**Comment by tasn** [comment]
Interesting. For me it works with the default lineage os contacts app on Android 7.1.
I'll try to figure this out. Thanks for the info.

Anything else you think may be useful for me to know?

**Comment by LogicalDash** [comment]
I just tested it with Simple Contacts and *that* seems able to edit the groups, but I can't really tell where it's saving these.

**Comment by tasn** [comment]
It should show in the journal after a sync.

**Comment by LogicalDash** [comment]
Ah, yeah, after adding some contacts to a group via Simple Contacts, that group shows up in the EteSync app proper.

**Comment by tasn** [comment]
OK, so it still needs fixing, but at least we know it works for you with a different app.

**Comment by victor-rds** [comment]
The same problem happens with default Samsung Contacts app on Android 8.0, also I don't know if this is related but when I tried do import a vcf file in this app I noticed that all vcard had the CATEGORIES field stripped, example:
```
BEGIN:VCARD
VERSION:4.0
UID:fd176145-954e-46a3-a5d2-49fadf8a4ecb
CATEGORIES:Family,Starred
FN:Given Other Family
N:Family;Given;Other;;
NICKNAME:nick
BDAY:01/01/1970
ORG:Organization
REV:20180528T084910Z
TEL;PREF;TYPE=CELL:555-5555
TEL;T;TYPE=WORK:555-4444
EMAIL:teste@gmail.com
EMAIL:teste@hotmail.com
END:VCARD
```
The `CATEGORIES:Family,Starred` disappeared, after that I tried to re-add the categories through Thunderbird Cardbook, with no success.

**Comment by tasn** [comment]
I think I fixed it. Could you please try using this version: https://stosb.com/~tom/app-release.apk

Sorry for the time it took.

**Comment by tasn** [comment]
@victor-rds, as for EteSync stripping categories: it's annoying and shouldn't happen, but an issue with etesync-dav, or maybe more correctly, the dav client (in this case tbird). EteSync uses the vcard 4 way of doing groups, which is a separate vcard for groups rather than the categories field. You should tell tbird to do the same, and then EteSync would work correctly. Please let me know if you manage to fix it so I can update the readme accordingly.

**Comment by tasn** [comment]
The issues described here should now be fixed (as confirmed by a few users). There are some related issues that are tracked in #54 so I'm closing this one.
