### ISSUE TITLE
Payment and e-mail response

### ISSUE THREAD

**Issue by M-u-m-p-i-t-z** [etesync/android#250]
I initiated a SEPA transfer for my account on 22.01.2024, which expires on 31.01.2024.
On 24.01.2024 I receive an email that my account is about to expire and I should enter a payment method in the dashboard.
I replied to this email that I had made a bank transfer and asked for this to be assigned to my account.
I have not received a reply to date, nor has my account been renewed. 
There are only 4 days left until I can still use the account, why have I not received a reply? Is the service still active?
At least a confirmation that you are looking at it would be appropriate.

Best regards

**Comment by tasn** [comment]
Apologies, will take a look now! SEPA (and PayPal) are processed manually so sometimes take a bit of time to be processed.

Closing this, as this is not the appropriate channel.
