### ISSUE TITLE
[new user experiencce] - consistent phrasing for user guide RE calendar front end on Android

### ISSUE THREAD

**Issue by quadrophobiac** [etesync/android#27]
Hello

As a new user who has installed etesync on Android (version ) and want to know how to add new calendars to my journal.

The user guide states the following for
Contacts: Add Contact
> You use the same contacts application you used previously

However a similar qualifying text is absent from the Calendar section. It can be inferred that this is what you mean by reading the rest of the user guide but I also think this could produce confusion.

Would suggest amending to 

> You use the same calendar application you used previously. This workflow may look different to the accompanying screenshots depending on which calendar application you use, but the concept is similar.

**Comment by tasn** [comment]
Done, would it be OK if I added you as a contributor to the about page? If so, under what name?

Thanks!
