### ISSUE TITLE
Crash on long-pressing action bar icon

### ISSUE THREAD

**Issue by Nuntius0** [etesync/android#30]
**Steps to reproduce:**
* Long press any action bar icon
* Ignore prompt to send developers the stack trace via email but capture a logcat and post it right here instead (do say if you can't reproduce this and need the stack trace!):

`ACRA caught a NoSuchFieldError for com.etesync.syncadapter
java.lang.NoSuchFieldError: No field message of type I in class Landroid/support/v7/appcompat/R$id; or its superclasses (declaration of 'android.support.v7.appcompat.R$id' appears in /data/app/com.etesync.syncadapter-1/base.apk)
	at android.support.v7.widget.TooltipPopup.<init>(TooltipPopup.java:60)
	at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:154)
	at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:103)
	at android.view.View.performLongClickInternal(View.java:5714)
	at android.view.View.performLongClick(View.java:5672)
	at android.widget.TextView.performLongClick(TextView.java:9415)
	at android.view.View.performLongClick(View.java:5690)
	at android.view.View$CheckForLongPress.run(View.java:22402)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Expected behaviour:**
Display label name (e.g. _Settings_ when long pressing the gearwheel). Try other Android apps to see what it looks like. I think this is (usually) handle by the action bar itself when the resource name is specified?

**Comment by tasn** [comment]
Thanks for reporting.
I just opened the app and tried it. Works for me and displays the label as expected.

Could you please provide more information regarding your setup? Did you get the app from the play store or fdroid? What's your OS version? Manufacturer? Etc?

**Comment by Nuntius0** [comment]
Lineage OS 14.1/Android 7.1.2
LG G6 (h870)
EteSync from F-Droid v0.20.4
I should know better, but always forget to post those :pensive: 
Also, I'm selfhosting, if that matters in any way.

**Comment by tasn** [comment]
Thanks.

Self-hosting: doesn't matter.
Lineage: I'm also using latest, so shouldn't matter.
EteSync: are you able to test if this also happens with EteSync from the play store? Or are you already using EteSync as your daily driver?

**Comment by Nuntius0** [comment]
I tested two more things: On my tablet with Lineage 15.1 it works correctly. Also on my phone (as above) it works fine with DAVdroid (v1.11.4.1-ose from F-Droid).
With EteSync from PlayStore (installed via Aurora Store) it, too, crashes.

No, I just started using EteSync yesterday. Well, "using" is maybe too much of a word here, I started playing around with it and learning how to setup the server with ningx and everything.

Also, since it now seems more like a bug specific to my setup, I just emailed you the stacktrace, in case that is any help.

**Comment by tasn** [comment]
Ah oops, I'm also on 15.1 not 14.1 (though I've tested it before on that
too).

Thanks for the stacktrace, will try to get to it soon, though it's a bit of
a low priority issue because of the scope and impact. I honestly have no
idea what's going on... Will try to maybe Google later.

**Comment by Nuntius0** [comment]
Yeah, don't worry, it's not that important at all. I doubt many users even know that they can get to the name of an icon's function by long pressing it...
I'll enjoy EteSync anyway :)

**Comment by tasn** [comment]
I still can't get it to happen here. :|

I'm going to close it for now, a lot has changed, and for all I see it works. If someone else is also getting this, please re-open.

**Comment by tasn** [comment]
Yay. :)

I really suspect it was something with your device...
