### ISSUE TITLE
Contacts lost on address book rename

### ISSUE THREAD

**Issue by face0b1101** [etesync/android#31]
I'm using the android app and decided to rename my main address book.

On doing so I lost all my contacts - the journal shows them all being deleted.

It's rather frustrating seeing all my contacts present and correct in the journal, is there any way I can export them at the moment?

**Comment by tasn** [comment]
It's more likely an issue with a specific Android version/manufacturer than in EteSync itself. I specifically remember this working and being tested locally.

As for your issue: if your journals look intact (as in, all of the data is there), the best workaround for now would be to just re-install EteSync, that would correctly re-sync all of your data onto your Android device and fix your issue. No need to export or anything. EteSync has a journal, so no data that has been written to the journal is ever lost, so as long as it's in the journal, it's fine.

For an extra reassurance measure, you can log into https://client.etesync.com and verify that all of your data is there.

Please let me know if the above doesn't work for some reason.

Sorry for the trouble.

**Comment by face0b1101** [comment]
It's no trouble, I understand that things are still in development. 
Of course I backed up all my contacts first!

I'll try the reinstall and see how it goes.

Cheers

**Comment by face0b1101** [comment]
Spot on. Reinstalling worked a treat.

**Comment by tasn** [comment]
Glad to hear.

**Comment by Dremet** [comment]
My contacts were lost on my Android device as well. I did rename the journal as well, if I remember correctly. Reinstalling also helped.

**Comment by tasn** [comment]
The rename is done in a bit of a hacky way, so I'm not surprised it dosen't work on some devices. I guess the solution would be to implement it properly. Though as discovered by you, EteSync never loses data. It's always there in the journal, and a fresh start (reinstall of the app) is usually sufficient to fix most Android oddities on the rare occasions when they happen.

**Comment by tjanez** [comment]
Just noting that I experienced a similar "loss" of contacts today after renaming the Address Book.

I'm using EteSync 2.3.0.

Simply removing my account from EteSync and re-adding it solved the issue.
