### ISSUE TITLE
create calendar for contact birthdays

### ISSUE THREAD

**Issue by stuart12** [etesync/android#32]
OwnCloud has a CalDAV URL to create an extra calendar automatically filled with my contacts' birthdays.
Could the etesync app automatically create an extra calendar of my contacts' birthdays?

**Comment by tasn** [comment]
Thanks for the suggestion, though unfortunately this is a bit of out scope for EteSync.
Luckily though, it doesn't need to be part of the package to get the functionality. You can just use https://f-droid.org/en/packages/org.birthdayadapter/ (I use it too).
It does exactly what you want.

Hope this helps.

**Comment by betsythefc** [comment]
I think this would be a cool as a setting, not necessarily a journal. Just a slider option for "Birthday calendar" in the app. It could either just read the contacts from Android, or read the journals in the app.

**Comment by DanielNetoP** [comment]
Is this something that's still planned for the future?
It would be better to have just etesync instead of using a different app for that

**Comment by tasn** [comment]
I agree, and it's definitely something I want to have too... Just need to find the time!

**Comment by danielfm** [comment]
I think having to install a separate app for that. The whole point of etesync is to use a fully encrypted service for handling contact and calendar data, but now I have to install a separate app (that I would need to inspect the source code just to make sure my contact information is not uploaded anywhere or used in a way I don't approve) just to get the birthdays into my calendar.

**Comment by tasn** [comment]
You don't need to inspect that app because it doesn't have any network permissions (or any additional permissions at all). Though I agree, it would be great to have this in the app.

**Comment by mo-st** [comment]
Hi, sorry but to clarify: Was this implemented and merged in [PR 159](https://github.com/etesync/etesync-web/pull/159) and I just can't find in the pim or is it actually not present? Thanks for the help, great piece of software!
