### ISSUE TITLE
Adding Members to Calendar fails

### ISSUE THREAD

**Issue by face0b1101** [etesync/android#37]
I've been running etesync on two android devices for a while now - it's working really well.

However, I have just tried to add a member to one of my calendars and it fails with an error message "Error Adding Member".

The member I am adding exists, I have confirmed the security fingerprint, and I am already a member on one of their calendars. I'm not sure what else I can try out - other than opening an issue.

Any help would be much appreciated - let me know what details you need.

**Comment by tasn** [comment]
Could you please contact support at support@etesync.com ?
I'd need to know your account and the other account, and I assume you'd rather not post them here.

Thanks.
