### ISSUE TITLE
Web App can only modify one calendar

### ISSUE THREAD

**Issue by face0b1101** [etesync/android#45]
~~I have just tried using the Web App to modify calendar entries.~~

~~Although it correctly displays my six calendars, and I can edit existing entries with no problems, I can only create new events on one of the calendars. All the calendars can be selected in the drop down menu, however it always selects and reverts to the same calendar each time. This calendar is neither the first or last calendar I created, and it happens to be a shared calendar if that makes a difference.~~

~~Am I doing something wrong?~~

I just realised I've posted this in the Android app issues, sorry.

Closing.

**Comment by tasn** [comment]
Thanks for moving this. :)
