### ISSUE TITLE
Constant pop-up notification 'etesync has crashed please send stack trace to developer'

### ISSUE THREAD

**Issue by Networkguy09** [etesync/android#51]
Getting a constant pop-up notification on my phone saying, 'etesync has crashed please send stack trace to developer'

This is happening without being in the etesync app, just when unlocking my phone, or surfing other apps within my phone. The pop-up happens several times a day. No debug file is being provided to be able to send to the developer. In other words, when the pop-up occurs there is no way to respond to it or take any action on it. It simply pops-up letting me know etesync is crashing (again). It crashes constantly, if you believe this message.

**Comment by tasn** [comment]
Thanks for reporting. EteSync doesn't need to be open to generate errors, as EteSync is a service that's running in the background (syncs your PIM). It's very weird that you're not getting the email application opened as it's the same workflow.

A couple of questions:
1. What's your android version?
2. Default email client? Is it Gmail, Samsung mail, Protonmail?

Additionally, please go to Settings -> Debugging and enable "Log to external file". Let the error happen a few times, and then please send me the file via email. It may contain sensitive information, so better to not post it here. Please also redact anything you'd rather me not see.

Sorry for this. :(

**Comment by Networkguy09** [comment]
1. 8.0.0
2. When going under apps > default apps, there is not even a place to define a default email app. The e-mail apps I use don't have anything to do with tie in to etesync contacts and calendar. For the contact and calendar I am using the stock Samgsung installed apps. I do use other e-mail apps like Outlook and Protonmail

I will check on the logging you requested.

**Comment by tasn** [comment]
Ah! I wonder if the Samsung app is just being funny and doesn't accept email intents. I assume you have a google account (because of the play store). Could you please try installing Gmail and seeing if it opens the mail client then?

Thanks!

**Comment by Networkguy09** [comment]
Gmail is already installed. Which mail client do you want me to try and open? I am able to open all three of the mail clients I use (Outlook, Proton, and Gmail). Not sure what the mail clients have to do with etesync?

**Comment by tasn** [comment]
My suspicion is that EteSync is crashing (for whatever reason) and then it tries to open the default mail client to send a crash report, but the default mail client in your case (Outlook? Samsung mail?) isn't opening for some reason.

Which clients opens when you click [this link](mailto:test@test.com)?

**Comment by Networkguy09** [comment]
Protonmail. However, if I go to my contacts list and select a contact with an email address listed, click the address, I get a prompt to select my client for either one time or always use that client. I tried uninstalling protonmail and waited for etesync to crash. It's given the crash message twice within a few minutes. No change. I also noted etesync sometimes gives the message if I launch etesync and click the sync icon (two arrows in a circle pointing counter clock wise)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Networkguy09** [comment]
Also I checked for logging and debugging under settings and dont see this on my phone.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tasn** [comment]
Sorry for the delay, I thought I already replied!
I'm talking about the EteSync app settings. Open the menu (top left hamburger icon) -> Settings -> scroll down until you see the logging to file.

EteSync syncs in the background, and when you click "sync", so it makes sense it would pop this message in the background and when you click sync as both are just syncing operations.

**Comment by Networkguy09** [comment]
This seems to have stopped happening. Its strange because it was so frequent. Literally happening every time I just unlock my phone. Let me give it some more time to see if it's really stabilized.

**Comment by tasn** [comment]
Have you changed anything? I fixed issues in the code handling event invites (events with guests), maybe it's related?

**Comment by Networkguy09** [comment]
No change

**Comment by tasn** [comment]
Have you reinstalled the app? Literally anything?

**Comment by Networkguy09** [comment]
No

**Comment by tasn** [comment]
Weird, so it just one day stopped? It doesn't even happen when you explicitly click "sync"?

I'm baffled, but happy it's working.

**Comment by tasn** [comment]
Oops, I forgot there was a ticket for this. I'm pretty sure I fixed this. New version is now out and it should work.

This seems to have affected a very small number of people (but not just you!).

Thanks again for reporting!
