### ISSUE TITLE
Import vCard from file crashes or returns "Empty/invalid file"

### ISSUE THREAD

**Issue by justjulian** [etesync/android#53]
I have a vCard stored locally in my phone that I would like to import, it just contains one contact. I tried importing it with the stock contact app to a etesync address book which worked. Importing this same file by using the etesync app itself however does not work.
From within an address book I tap Import --> From File, I get the following options

![2018-12-27 12 43 54](https://user-images.githubusercontent.com/788673/50479911-49aae300-09d9-11e9-8c52-9a316b880fd9.png)

I tried the following options and include the log files for it:

[1] Huawei CAN-L11
[etesync-4807-20181227-124727-huaweicanl11.txt](https://github.com/etesync/android/files/2712383/etesync-4807-20181227-124727-huaweicanl11.txt)
[2] Internal Storage
[etesync-4562-20181227-124531-internalstorage.txt](https://github.com/etesync/android/files/2712386/etesync-4562-20181227-124531-internalstorage.txt)
[3] Files
[etesync-4688-20181227-124634-files.txt](https://github.com/etesync/android/files/2712388/etesync-4688-20181227-124634-files.txt)
[4] Total Commander
[etesync-4231-20181227-124306-totalcommander.txt](https://github.com/etesync/android/files/2712390/etesync-4231-20181227-124306-totalcommander.txt)

Note that with [2] it is using the Stackfield app on my phone to access the content which I think is pretty weird.
Options [1] and [4] return an error in the app: Empty/invalid file
Options [2] and [3] result in a stuck app with the following screen

![2018-12-27 12 39 56](https://user-images.githubusercontent.com/788673/50480071-31879380-09da-11e9-86b5-275eebed7faf.png)

As mentioned, this vCard is valid and could be imported with the stock contact app. Therefore I would expect this should also work from within etesync.

Android version 7.0
EMUI version 5.0.3
Model Number Huawei CAN-L11

**Comment by justjulian** [comment]
I deleted the address book and tried the import on a fresh one. That worked. Can be closed if no one thinks that it should be analyzed further.

**Comment by tasn** [comment]
Sorry I didn't get to it before. I think it's still worth investigating, or at least I should try to reproduce it. It seems like EteSync wasn't able to access the file before, but is able to access it now? You can't reproduce it anymore, right?

**Comment by justjulian** [comment]
Correct, I cannot reproduce it anymore.
Though, in the meantime I also upgraded from 0.22.3 to 0.22.4. Could be related.

**Comment by tasn** [comment]
Would you mind sending me the vcard (support@etesync.com) in question? Please feel free to filter out any information you deem private, e.g. replace the name from Tom to -> Aaa. Just please keep the character count similar (i.e replace one letter for one), if there are unicode chars, maintain them as much as possible, and etc. Same goes for phone numbers.

This could help a lot.

As for the upgrade: there has been a tiny fix touching contacts that could be relevant if the contact has a group (sometimes called label) associated.

**Comment by justjulian** [comment]
Hi Tom and sorry for the late reply. I'm afraid that this would take too much time to replace all private information. It's over 100 contacts with emails, phone numbers, and addresses. The file contains 1184 lines with a character count of 23922. A typical example looks like this:
```
BEGIN:VCARD
VERSION:4.0
FN:FirstName LastName
N:LastName;FirstName;;Dr.;
CATEGORIES:Misc
GENDER:F
TEL;PREF=1;TYPE=home:+4111111111111
TEL;PREF=2;TYPE=work:+4111111111112
EMAIL;PREF=1;TYPE=home:name@example.com
EMAIL;PREF=2;TYPE=home:name@otherexample.com
ADR;PREF=1;TYPE=home:;;Street number;city;;zip;country
BDAY:1960-01-01
END:VCARD
```
I would recommend to extend the error message in case this happens again (as I cannot reproduce it anymore) and then if it happens again we have hopefully more information on this.
