### ISSUE TITLE
Duplicate contact groups

### ISSUE THREAD

**Issue by dcasado** [etesync/android#57]
I have been messing with groups and contacts in different applications and something very strange has happened. After I created and edited a group it has duplicated itself. Now I have more than one copy of the group with different number of contacts inside. Also I tried to delete them and they show in the journal with the same id.

In this image you can see the duplicate groups all with same name and different number of contacts
![photo_2019-01-09_17-16-51](https://user-images.githubusercontent.com/10188511/50912519-a6bf8380-1432-11e9-8f2d-29846ebdaa62.jpg)

In this image you can see various groups with the same name and uid been deleted multiple times although they where only created once. I marked them with red and purple crosses to see them better.
![photo_2019-01-09_17-16-38](https://user-images.githubusercontent.com/10188511/50912776-38c78c00-1433-11e9-81e3-764a9b8b0e36.jpg)

Device: Oneplus 6
Android version: 9
Etesync version: 0.22.6
Contacts application: Default Oneplus contacts app

**Comment by tasn** [comment]
Thanks for reporting, and sorry for that! I recently fixed a related bug, I'll try to figure it out.
It's weird that a group is being duplicated even though it has the same UID.

With that being said, I recently overhauled that code, can you try with version 0.24.1 (latest) and see if it still happens? Edit the group, and essentially do what you did, and see if it duplicates again.

**Comment by dcasado** [comment]
First, thanks to you for developing this awesome application and helping me solve this issues!

I'm using etesync from f-droid and last version of your app is not there yet, I will try once I can update the app.

**Comment by tasn** [comment]
Looking forward to hearing back, thanks!

Also, once you're on the Google Play version I can send you signed test apps with debug information to try.

**Comment by tasn** [comment]
Hey, I'm closing this as I assume it's now fixed (as previously mentioned). Please reopen if it's not the case.
