### ISSUE TITLE
F-Droid Not Being Updated

### ISSUE THREAD

**Issue by forty8bits** [etesync/android#59]
I realise that F-Droid releases are expected to lag behind the Google Play Store to some degree, and that there's been a high number of releases in a short time over the past few weeks, but the F-Droid release appears to be 7 releases / 9 days behind currently, which seems excessive.

**Comment by tasn** [comment]
Yeah, it was driving me mad, but it's now been resolved. An update should be available by tomorrow or the day after.

I have more features I'd like to release, but I can't update the server until f-droid is updated, so I really can't wait! :(

Anyhow, closing this for now as it's has already been taken care of. Please reopen if it doesn't get updated within the next few days (though I'm also watching it closely).

**Comment by tasn** [comment]
It's still taking longer than expected. Grrr!
It should update this page once it's actually done: https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.etesync.syncadapter.txt
And we are waiting for this to run again already so it updates the previous one: https://f-droid.org/wiki/index.php?title=checkupdates

**Comment by tasn** [comment]
It finally picked up the new version. Let's just hope the build goes through smoothly, and hopefully it'll be on F-Droid today or tomorrow. \o/

**Comment by tasn** [comment]
It's finally out! :tada: :tada: :tada:
