### ISSUE TITLE
Setting colour for tasks lists doesn't work

### ISSUE THREAD

**Issue by forty8bits** [etesync/android#60]
Tasks support is a great addition. :ballot_box_with_check: One minor issue I've noticed is that (as of EteSync 1.0.1) setting the colour on tasks lists doesn't work. To reproduce, simply edit the tasks list, change the colour and select save; you should then see the colour unchanged when returned to the previous screen.

**Comment by tasn** [comment]
Oops, fixed, thanks for reporting!

I just released version 1.0.2 which should be available on the play store shortly and f-droid soon too (I hope).
