### ISSUE TITLE
Possible to add note-taking feature as well into this?

### ISSUE THREAD

**Issue by 60Eight** [etesync/android#62]
First of all, thanks for this wonderful project. This app has been a joy to use for contacts & calendar management.
I recently started using the tasks management feature as well and it's great. Wondering if note-taking feature can also be included somehow?

**Comment by tasn** [comment]
Yes it can, and I'm also dying to have it. :)
With that being said, there are a few things that will probably be done before, so can't make any promises with regards to an ETA unfortunately. Sorry.

**Comment by 60Eight** [comment]
Glad to know that. Thanks for the work you're putting into this, this is a great (secure) syncing solution. :+1: :tada: 

I don't even remember the last time I opened the app, all the magic happens behind the scenes. :smile:

**Comment by tasn** [comment]
Haha, yeah, that's part of the magic. :)

**Comment by 60Eight** [comment]
Hey! Just checking in to see if you looked into this further. I've been using Orgzly since a couple of months, would love if we could find a solution that'd work with that as the note-taking app.

**Comment by tasn** [comment]
No, unfortunately. The next main task is an iOS client and this will probably not happen before then. There's some more information in #87 about an orgzly integration, but unfortunately there hasn't been any progress on this matter. Sorry. :|

**Comment by 60Eight** [comment]
Thanks for the response.
I see the PR mentioned in that issue has been merged in Orgzly. Does that mean work on supporting it in eteSync can start?

**Comment by tasn** [comment]
That PR is a very good start, and I'm happy to help anyone who's looking into implementing it!
Though unfortunately that can't be me for at least the next month and a half. :|

**Comment by 60Eight** [comment]
Would it be possible for you to detail what exactly needs to be done to implement it. I not have any Android development experience but I give it a try if it's just implementing a few classes.

**Comment by 60Eight** [comment]
@tasn Would it be possible for you to detail what exactly needs to be done to implement it? I not have any Android development experience but I give it a try if it's just implementing a few classes.

**Comment by tasn** [comment]
Sure. Here is the high level description, and I'm happy to go into deeper details as you progress:
That PR implements webdav sync, which is essentially file upload. You can take that as an example, and replace every DAV operation with the EteSync equivalent.
The basic EteSync handling code is available in this repo under: `app/src/main/java/com/etesync/syncadapter/journalmanager/` and in a sense also `resource/` but that's for a later stage.

I think you should first figure out how to do the above (shouldn't be too hard), and after that we would probably need to write a layer that converts between the orgzly internal format and vcard, so it's written in the same format that etesync-dav and etesync-web expect.

I know it's very high level. If you are on IRC I'm happy to answer your questions as you have them.

**Comment by 60Eight** [comment]
Sorry guys, I'm no longer working on this. It isn't as trivial as I hoped it to be.

**Comment by tasn** [comment]
Yeah, it's not trivial. It's something I'm really hoping to address soon though!

**Comment by tasn** [comment]
Done: https://blog.etesync.com/introducing-etesync-notes/

**Comment by 60Eight** [comment]
Awesome work @tasn
