### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by Nuntius0** [etesync/android#65]
**What?** Make the app icon adaptive.

**Why?** If we like it or not, it's where Android is going. I stumbled upon it again now that in Lineage 16.0's Trebuchet the option to not force adaptive icons is gone.

**Details**
See the [Android dev guide](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) for a start.

Using Android Studio's Image Asset Tool it is actually quite simple, just choose a background color and a foreground icon. The design of the latter is the hard bit for icons like EteSync's or F-Droid's, which so far featured a custom shape.

**Comment by tasn** [comment]
Thanks! I'll try to get to it sometime soon, though it's not a priority. I also need to figure out what I want, though I guess I may just go with a black background and keep the foreground icon exactly what it is.
