### ISSUE TITLE
Unable to add another etesync account as a member on tasks and calendars. Other member can add me. 

### ISSUE THREAD

**Issue by face0b1101** [etesync/android#68]
I have started using etesync for creating tasks, thanks for adding the feature.

Unfortunately, I'm having a problem adding members to task lists, similar to what I experienced in issue #37 (solved by #46).

Even more unfortunately, it doesn't work even when I change the case of the email as I did before. The issue I had with emails (#37) also appears to be back in play - I can't add members. 

Any chance there might be an obvious reason this is happening, or am I just doing it wrong again? Last time it was to do with case sensitivity. 

For clarification; 
1. I am unable to add members to tasks or calendars. I get a simple error message, "error adding member".
2. The member I am trying to add exists, and the fingerprint is correct. 
3. Case sensitivity doesn't appear to be the issue this time. 
4. I have only tried adding one specific etesync account, I don't have others to try. 
5. The other account is able to add me. 

@tasn I don't know if you still have my account details from when I raised #37? It's the same accounts I'm having difficulty with this time.

**Comment by tasn** [comment]
I don't. Please email me your account name, and the other member's account name.

**Comment by tasn** [comment]
Fixed. It was a problem with the hosted service not handling email casing correctly. Thanks for reporting!
