### ISSUE TITLE
Excessive battery usage in 1.5.0

### ISSUE THREAD

**Issue by stevesbrain** [etesync/android#82]
Since the update to 1.5.0, my battery usage has jumped quite a bit (6% in 8 hours, syncing only once per hour). Anything I can do to help troubleshoot this?

**Comment by tasn** [comment]
I'd say first try restarting your phone, maybe some Android mechanism is acting up. If that doesn't work, please got to Settings and enable debug to file and verbose debug, let it waste a bit of battery and then send me (my first name @etesync.com) the log file after you've verified there's no personal information there.

**Comment by stevesbrain** [comment]
Shall do - will get that for you if I can replicate after that!

**Comment by tasn** [comment]
Any updates?

**Comment by stevesbrain** [comment]
Sorry, just wanted to give it a coule of days to be sure - battery usage has been much more normal since, so just a bit of a glitch I think! I'll close it off for now :)

**Comment by tasn** [comment]
Glad to see it's all working, and thanks for the update!
