### ISSUE TITLE
Encryption password won't work on second device 

### ISSUE THREAD

**Issue by Aflakete** [etesync/android#89]
On my Sony Compact phone, it keeps saying encryption password I set up on my Huawei tablet is wrong.

**Comment by tasn** [comment]
I assume you still have access to the first device, correct? First of all, please do NOT uninstall the app from there, or try changing your encryption password.

Take a look at the main etesync screen on your tablet, you'll see your email address. Could you make sure to use the same capitalization (upper/lower case) you used there on your phone too? Emails are case sensitive and annoyingly we rely on that in EteSync. Something I plan on fixing very soon!

**Comment by Aflakete** [comment]
Nice catch. My tablet somehow defaulted to capitalizing the first letter of my email address. That worked. Thanks for the quick reply.

**Comment by tasn** [comment]
Glad to hear! This is such an annoying issue I just can't wait to fix already... :|
