### ISSUE TITLE
Contacts No Longer Syncing After Upgrade To 1.8.2

### ISSUE THREAD

**Issue by quantumpacket** [etesync/android#92]
I'm not sure if I was on `1.8.0` or `1.8.1` prior to the upgrade, but once I upgraded to `1.8.2` my calendar and contacts are no longer available. Etesync allows me to synchronize, and no errors are thrown, but nothing gets downloaded. The data is there as my desktop can still access both.

On a side note, if I try to downgrade through F-Droid via the versions tab, I get "Failed to install due to unknown error".

Please let me know what other information I can provide to help debug.

**Comment by tasn** [comment]
Let's first try to figure out which one is not syncing. The desktop or Android.
Could you access https://client.etesync.com and see if your data is even there? If it isn't, it's your desktop client that's not working.
If it is, could you please open the Android client -> Side menu, and then enable verbose logging and log to file, try to sync manually (sync button in the account page in the app), and see if you get any interesting errors in the logs?

Thanks!

**Comment by quantumpacket** [comment]
@tasn I logged into the above link and I can see my calendars and contacts. Both are syncing to my desktop on Thundrbird, but Etesync on Android is only syncing the calendar. 

But here is the weird part. I can see my change journal for the contacts via the app. So it is syncing as even new changes show up. Even weirder, is when I add the contact called _TESTING_ it shows up in the change journal **and** displays in my contacts normally, but all older entries are not...even thought the website says they are all there.

I'll gist a copy of my debug log, but gotta find some time to redact stuff.

**Comment by tasn** [comment]
Just to rehash what you said: contacts sync works fine on Android except for a few old entries that don't show on your Android device? If you create new ones on either Android or the desktop it shows correctly on the phone?

I'd suggest trying uninstalling and reinstalling (make sure your data is properly synced before you do, because any unsynced changes will be lost). It's not a solution, but I've seen sync stopping to work before and reinstall fixed it. I'd have to get to the bottom of this when I finally managed to reproduce it here.

**Comment by quantumpacket** [comment]
@tasn Not exactly, **all** my contacts are not showing up on Android, but if I add a new one via the website the new entry shows up. My missing contacts which still exist don't, even thought the file is being synced according to the updated journal I can see in Android.

I'll do an uninstall and reinstall and hopefully it fixes it.

**Comment by tasn** [comment]
OK, so all the old ones don't show, but new ones (created on the device or remotely) work just fine. Is this correct?

Anyhow, please let me know once you've tried reinstalling. Thanks!

**Comment by quantumpacket** [comment]
Yeah, only new entries show up on the app, but all entries show up on the website.

Anyways, I did uninstall and reinstall and everything seems to be working now. I guess we will never know what caused this weird behavior. Closing this as reproducing it is going to be difficult. Thanks for the help.

**Comment by tasn** [comment]
Yay. \o/

Yeah, I'm baffled. I've seen this one before, but I don't even know where to start debugging it. Have you maybe renamed the contact list at some point? I think what happens is that at some point it just stops working but EteSync thinks it did work so it never tries again. :|

**Comment by quantumpacket** [comment]
Nope, just did the update and then it broke. :(

**Comment by tasn** [comment]
OK, no idea. :)
Let me know if it ever happens again/you find more info.
