### ISSUE TITLE
Option to enable contact/calendar/task sync separately

### ISSUE THREAD

**Issue by DeWir3** [etesync/android#94]
I recently installed etesync on my tablet, where I want to sync calendars and task lists, but not contacts. The only way of doing that I found is just denying etesync access to the contacts on the device. While that works, it produces a notification with an error message that it couldn't sync the contacts every time it syncs. It would be a great addition, if you could choose which of those three to sync individually.

**Comment by tasn** [comment]
Thanks for opening this ticket!

This is already covered in #48 (I just updated the title to make it more informative), so I'm closing this one.
